name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install UV
      uses: astral-sh/setup-uv@v2
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r pyproject.toml
    
    - name: Check code formatting
      run: |
        uv pip install black ruff
        uv run black --check src/ || true
        uv run ruff check src/ || true
    
    - name: Run basic tests
      run: |
        python -c "import pandas; import sklearn; print('✅ Dependencies OK')"

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t attrition-mlops:latest .
    
    - name: Test Docker image
      run: |
        docker run -d --name test-app -p 8000:8000 attrition-mlops:latest
        sleep 15
        curl -f http://localhost:8000/health || exit 1
        docker stop test-app
        docker rm test-app